version: '3'

services:
  portfoliomyriam:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:DefaultConnection=Server=portfolio-db;Port=5432;Database=portfolio;Username=postgres;Password=postgres
      - AppSettings:AdminEmail=admin@example.com
      - AppSettings:AdminPassword=Admin1!
      - AppSettings:GuestPassword=Guest1!
    ports:
      - "80"

  portfolio-db:
    container_name: portfolio-db
    image: mdillon/postgis:9.6
    volumes:
        - portfolio-postgres-data:/var/lib/postgresql/data
        - portfolio-postgres-log:/var/log/postgresql
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=portfolio
      - TZ=EST

volumes:
  portfolio-postgres-data:
  portfolio-postgres-log: