version: '3'

services:
  portfoliomyriam:
    image: vmeijer/portfolio-myriam
    build:
      context: .
      dockerfile: PortfolioMyriam/Dockerfile
    environment:
      - PORTFOLIO_DB_HOST=
      - PORTFOLIO_DB_PORT=5432
      - PORTFOLIO_DB_USER=
      - PORTFOLIO_DB_PASSWORD=
      - POSTGRES_DB=portfolio
      - ADMIN_PASSWORD=
      - GUEST_PASSWORD=
