version: '3'

services:
  portfoliomyriam:
    image: vmeijer/portfolio-myriam
    build:
      context: .
      dockerfile: PortfolioMyriam/Dockerfile
    environment:
      - ConnectionStrings:DefaultConnection=
      - AppSettings:AdminEmail=
      - AppSettings:AdminPassword=
      - AppSettings:GuestPassword=
