version: '3'

services:
  portfoliomyriam:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PORTFOLIO_DB_HOST=portfolio-db
      - PORTFOLIO_DB_PORT=5432
      - PORTFOLIO_DB_USER=postgres
      - PORTFOLIO_DB_PASSWORD=postgres
      - ADMIN_PASSWORD=Admin1!
      - GUEST_PASSWORD=Guest1!
    ports:
      - "80"

  portfolio-db:
    container_name: portfolio-db
    image: mdillon/postgis:9.6
    volumes:
        - portfolio-postgres-data:/var/lib/postgresql/data
        - portfolio-postgres-log:/var/log/postgresql
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - TZ=EST

volumes:
  portfolio-postgres-data:
  portfolio-postgres-log: